### PR TITLE
Option to fix hyperparameters in hbmcmc code.

### PR DESCRIPTION
**Pull request by wardrebecca**
Linked to issue #104. Adds option to fix hyperparameters in hbmcmc code using an input where you specify the sigprior pdf as ‘fixed’ with its fixed value.

Also added offset option to the ini file.

Type of Change: New feature

Checklist: Code documentation has been updated if needed

### CODE REVIEW

**Comment by rebeccawardbristol** [comment]
Previous comments from Luke on BitBucket:

A few things I’d ask:

- Get rid of the print statement (line 196 and 206, inversion_pymc3)
- Introducing the new variable “sigma_flux” seems unneeded when you can just use ‘if sigprior[“pdf”] == “fixed”’. Would be good to shorted the code and avoid adding new variables

Can you avoid some of the if statements by: Building “fixed” into the parsePrior function, so that fixed_value is returned? You then wouldn’t need the if statement and extra code. Instead of having an “if” and all the output copy and pasted when using a fixed value, you could just make an array of e.g. NaNs for the array sigouts if sigprior[“pdf”] == “fixed”. That way it will run through as normal and save all the extra lines of code. Makes the output a little bigger than it is with what you’ve written, but I think that’s OK.

**Comment by rt17603** [comment]
@rebeccawardbristol @lukewestern - what is the status on this PR? Do the suggested changes still need to be incorporated or is this ready for re-review?

**Comment by rebeccawardbristol** [comment]
@rt17603, the changes still need to be incorporated. I'm not sure when I will get around to doing this at the moment.

**Comment by ag12733** [comment]
At the code retreat, we decided that this functionality would just go straight into the openghg_inversions repo rather than here. So this PR can be closed and not merged in.

**Pull request closed without merging**
