### PR TITLE
Update environment to Python 3.10, etc.

### PR DESCRIPTION
**Pull request by mrghg**
Updated packages to more recent versions, and fixed some bugs that cropped up along the way. Relates to this issue: https://bitbucket.org/mrghg/acrg/issues/78/upgrade-pinned-packages-in

All tests pass.

### CODE REVIEW

**Comment by hanchawn** [comment]
I get this error on test_name.test_fp_data_merge:

AttributeError: Can't get attribute 'PandasIndex' on <module 'xarray.core.indexes' from '/user/home/vf20487/.conda/envs/acrg/lib/python3.8/site-packages/xarray/core/indexes.py'>

**Comment by mrghg** [comment]
> I get this error on test_name.test_fp_data_merge:
> 
> AttributeError: Can't get attribute 'PandasIndex' on <module 'xarray.core.indexes' from '/user/home/vf20487/.conda/envs/acrg/lib/python3.8/site-packages/xarray/core/indexes.py'>

Yeah, this is a problem with one of the benchmarking files having been created with a different python version. Are you sure you're in the right environment?

**Comment by mrghg** [comment]
Note that this has now been updated to Python 3.10

**Comment by mrghg** [comment]
@lukewestern , please take a look at the change to inversion_pymc3, dealing with deprecated pymc3.stats.hpd

**Comment by mrghg** [comment]
> > I get this error on test_name.test_fp_data_merge:
> > AttributeError: Can't get attribute 'PandasIndex' on <module 'xarray.core.indexes' from '/user/home/vf20487/.conda/envs/acrg/lib/python3.8/site-packages/xarray/core/indexes.py'>
> 
> Yeah, this is a problem with one of the benchmarking files having been created with a different python version. Are you sure you're in the right environment?

Is it possible git isn't seeing that an update is needed to those files?

**Review by lukewestern — COMMENTED** [review]
The pymc3 changes look fine to me. Haven't tested the other bits.

**Comment by hanchawn** [comment]
> > I get this error on test_name.test_fp_data_merge:
> > AttributeError: Can't get attribute 'PandasIndex' on <module 'xarray.core.indexes' from '/user/home/vf20487/.conda/envs/acrg/lib/python3.8/site-packages/xarray/core/indexes.py'>
> 
> Yeah, this is a problem with one of the benchmarking files having been created with a different python version. Are you sure you're in the right environment?

Do I need to do anything other than deactivate and reactivate acrg?

**Comment by mrghg** [comment]
> > > I get this error on test_name.test_fp_data_merge:
> > > AttributeError: Can't get attribute 'PandasIndex' on <module 'xarray.core.indexes' from '/user/home/vf20487/.conda/envs/acrg/lib/python3.8/site-packages/xarray/core/indexes.py'>
> > 
> > 
> > Yeah, this is a problem with one of the benchmarking files having been created with a different python version. Are you sure you're in the right environment?
> 
> Do I need to do anything other than deactivate and reactivate acrg?

You'll need to rebuild your acrg environment (hopefully much quicker to do this now though)

**Comment by hanchawn** [comment]
I've rebuilt my environment and I'm getting some fails in test_hbmcmc:
FAILED tests/test_hbmcmc.py::test_hbmcmc_inputs - assert 1 == 0
FAILED tests/test_hbmcmc.py::test_hbmcmc_inputs_command_line - assert 1 == 0
FAILED tests/test_hbmcmc.py::test_hbmcmc_output_exists - AssertionError: assert False
FAILED tests/test_hbmcmc.py::test_hbmcmc_rerunoutput - FileNotFoundError: [Errno 2] No such file or directory: '/user/home/vf20487/code/acrg/tests/files/output/CH4_EUROPE_pytest-deleteifpresent_2014-02-01.ini'


and a weird one in test_name:
PermissionError: [Errno 13] Permission denied: b'/user/home/chxmr/code/acrg/tests/files/LPDM/fp_NAME_minimal/EUROPE/MHD-10magl_EUROPE_201402.nc'

**Comment by hanchawn** [comment]
I moved the .pth file from .local/lib/python3.8/site-packages/ into a new dir for python3.10 and test_hbmcmc passes now

**Comment by mrghg** [comment]
> I've rebuilt my environment and I'm getting some fails in test_hbmcmc: FAILED tests/test_hbmcmc.py::test_hbmcmc_inputs - assert 1 == 0 FAILED tests/test_hbmcmc.py::test_hbmcmc_inputs_command_line - assert 1 == 0 FAILED tests/test_hbmcmc.py::test_hbmcmc_output_exists - AssertionError: assert False FAILED tests/test_hbmcmc.py::test_hbmcmc_rerunoutput - FileNotFoundError: [Errno 2] No such file or directory: '/user/home/vf20487/code/acrg/tests/files/output/CH4_EUROPE_pytest-deleteifpresent_2014-02-01.ini'
> 
> and a weird one in test_name: PermissionError: [Errno 13] Permission denied: b'/user/home/chxmr/code/acrg/tests/files/LPDM/fp_NAME_minimal/EUROPE/MHD-10magl_EUROPE_201402.nc'

I think this was being caused by us pickling an xarray dataset that was not explicitly loaded into memory. Therefore, it was looking for a version that wasn't available on your system. I think I've fixed it in the latest commit, but please test again.

**Pull request merged**
